"""empty message

Revision ID: 76182135ccce
Revises: 2e75f31967be
Create Date: 2022-12-15 21:56:16.075702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76182135ccce'
down_revision = '2e75f31967be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_column('address')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.String(length=500),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('genres',
               existing_type=sa.String(length=500),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
